kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 9090
    hostPort: 19090  #for prometheus
    protocol: TCP
  - containerPort: 3000
    hostPort: 13000 #for grafana
    protocol: TCP
  - containerPort: 5601
    hostPort: 15601 #kibana
    protocol: TCP
  - containerPort: 9200
    hostPort: 19200 #elasticsearch
    protocol: TCP
  - containerPort: 80
    hostPort: 18080 #for our purpose
    protocol: TCP
- role: worker
- role: worker
